# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- task: Bash@3
  inputs:
    targetType: inline
    script: |
      cd $M2_HOME/boot
      ls -la
      rm ./plexus-classworlds.license
- task: ArtifactoryMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    artifactoryResolverService: 'rt-server'
    targetResolveReleaseRepo: 'slash-guide-maven-virtual'
    targetResolveSnapshotRepo: 'slash-guide-maven-virtual'
    artifactoryDeployService: 'rt-server'
    targetDeployReleaseRepo: 'slash-guide-maven-virtual'
    targetDeploySnapshotRepo: 'slash-guide-maven-virtual'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'rt-server'
    buildNumber: '$(Build.DefinitionName)'
    buildName: '$(Build.DefinitionName)'
    
